# docker-compose.yml
services:
   web:
      image: php:8-apache
      ports:
        - 80:80
      volumes:
        - ./public_html:/var/www/html
# docekr --version
# docker compose up -d
# docker compose down